# Generated by Django 4.2.1 on 2023-05-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='size',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
