# Generated by Django 4.2.1 on 2023-05-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_warehouse_size_warehouse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='price',
            field=models.IntegerField(),
        ),
    ]
