# Generated by Django 4.2.1 on 2023-05-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_warehouse_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50, null=True),
        ),
    ]
