# Generated by Django 4.2.1 on 2023-05-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_warehouse_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measure',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
