# Generated by Django 4.2.1 on 2023-05-31 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_measure_alter_product_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
