# Generated by Django 4.2.2 on 2023-06-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_incoming_price_product_arrival_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
