# Generated by Django 4.2.2 on 2023-07-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_addproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='paid',
            field=models.IntegerField(null=True),
        ),
    ]
