# Generated by Django 4.2.4 on 2023-08-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_addproduct_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='dealer_id',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='status',
        ),
    ]
