# Generated by Django 4.2.4 on 2023-08-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_addproduct_dealer_id_remove_addproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='price',
        ),
    ]
