# Generated by Django 4.2.1 on 2023-05-31 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer', '0002_remove_dealeroutput_worker'),
        ('product', '0010_delete_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField(null=True)),
                ('total_price', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50)),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
