# Generated by Django 4.2.1 on 2023-06-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
