# Generated by Django 4.2.1 on 2023-06-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='paid',
        ),
    ]
