# Generated by Django 4.2.2 on 2023-06-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_customerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
