# Generated by Django 4.2.2 on 2023-07-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_customerpayment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
