# Generated by Django 4.2.2 on 2023-07-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sale',
            field=models.IntegerField(null=True),
        ),
    ]
