# Generated by Django 4.2.4 on 2023-09-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_cost_user_costcategory_user_return_user_sell_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
