# Generated by Django 4.2 on 2023-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('sell', '0005_alter_sellitem_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Purchase',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='sellitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sellitem',
            name='discount',
        ),
        migrations.AddField(
            model_name='sell',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='ClientPay',
        ),
    ]
