# Generated by Django 4.2 on 2023-05-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_rename_payment_purchase_remove_cost_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
