# Generated by Django 4.2 on 2023-05-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_sellitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
