# Generated by Django 4.2.1 on 2023-05-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0008_purchase_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='checkout',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
