# Generated by Django 4.2.1 on 2023-05-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0009_sell_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
