# Generated by Django 4.2.1 on 2023-05-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0010_sell_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
