# Generated by Django 4.2.1 on 2023-06-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0011_delete_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='money',
            new_name='cost',
        ),
    ]
