# Generated by Django 4.2.1 on 2023-06-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0014_cost_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
