# Generated by Django 4.2.2 on 2023-06-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0015_sell_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
