# Generated by Django 4.2.2 on 2023-06-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0016_sellitem_discount_alter_sellitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
