# Generated by Django 4.2.1 on 2023-06-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0016_alter_sellitem_sell_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
