# Generated by Django 4.2.2 on 2023-06-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_customerpayment_date'),
        ('sell', '0017_alter_sellitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
    ]
