# Generated by Django 4.2.2 on 2023-06-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0019_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
