# Generated by Django 4.2.2 on 2023-06-14 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_worker_delete_customuser'),
        ('sell', '0020_return_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.worker'),
        ),
        migrations.AlterField(
            model_name='return',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.worker'),
        ),
    ]
