# Generated by Django 4.2.2 on 2023-07-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0021_alter_cost_worker_alter_return_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
