# Generated by Django 4.2.2 on 2023-07-15 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0022_alter_return_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='paid',
        ),
    ]
