# Generated by Django 4.2.2 on 2023-07-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0024_remove_sell_paid_return_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
