# Generated by Django 4.2.3 on 2023-07-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0025_sellitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
