# Generated by Django 4.2.3 on 2023-08-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0027_alter_sell_time_alter_sellitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
