# Generated by Django 4.2 on 2023-05-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealeroutput',
            name='worker',
        ),
    ]
