# Generated by Django 4.2.1 on 2023-06-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_rename_dealeroutput_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='price',
            new_name='payment',
        ),
    ]
