# Generated by Django 4.2.4 on 2023-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_rename_price_payment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='debt',
            field=models.IntegerField(null=True),
        ),
    ]
